"""adds Department

Revision ID: 27af0747252c
Revises: 3d2f144fde16
Create Date: 2024-11-17 23:19:56.439676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27af0747252c'
down_revision = '3d2f144fde16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
